attributes:

  password:
    type: "password"
    weight: 10
    value: ""
    label: "Admin password"
    description: "Type ScaleIO Admin password"
    regex:
      source: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$'
      error: "You must provide a password with between 8 and 15 characters, one uppercase, and one number"

  gw_password:
    type: "password"
    weight: 30
    value: ""
    label: "Gateway password"
    description: "Type a password for the gateway"
    regex:
      source: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$'
      error: "You must provide a password with between 8 and 15 characters, one uppercase, and one number"

  pool_size:
    type: "text"
    value: "100"
    label: "Storage pool size (in GB)"
    description: "Amount in GB that each node will contribute to the storage pool. Please make sure all nodes have enough disk space to allocate the provided amount."
    weight: 55
    regex:
      source: '^([1-9]\d\d|[1-9]\d{3,})$'
      error: 'You must provide a number greater than 100'

   version:
    type: "select"
    weight: 60
    value: "1.32"
    label: "Version"
    description: "Select the ScaleIO version you wish to install"
    values:
      - data: "1.32"
        label: "1.32"
      - data: "2.0"
        label: "2.0"
